

disabled_rules: # rule identifiers to exclude from running

identifier_name:
  excluded: # excluded via string array
    - id

trailing_whitespace:
  ignores_empty_lines: true

type_name:
  allowed_symbols: ["_"] # these are allowed in type names
